

#todo Find the Difference
# ? You are given two strings s and t. String t is generated by randomly shuffling string s and then adding one more letter at a random position. 
# ? Return the letter that was added to t.

# * Examples
# ?find_the_difference("abcd", "abcde") ➞ "e"

# ?find_the_difference("", "y") ➞ "y"

# ?find_the_difference("ae", "aea") ➞ "a"
#! Notes
#* N/A



# def find_the_difference(s, t):
#     stri = ""
#     for x in s:
#         if x not in t:
#             stri += x
#     return stri
# print(find_the_difference("abcd", "abcde"))



def find_the_difference(s, t):
    for char in t:
        if t.count(char) > s.count(char):
            return char

# Test case
print(find_the_difference("abcd", "abcde"))  # ➞ "e"
print(find_the_difference("", "y"))